# Generated by Django 5.0.6 on 2024-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uzb', models.TextField()),
                ('question_rus', models.TextField()),
                ('question_eng', models.TextField()),
                ('answer_uzb', models.TextField()),
                ('answer_rus', models.TextField()),
                ('answer_eng', models.TextField()),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faqs',
                'db_table': 'faq',
            },
        ),
    ]
