# Generated by Django 5.0.6 on 2024-05-18 13:33

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title_uz', models.CharField(max_length=250)),
                ('paper_title_ru', models.CharField(max_length=250)),
                ('paper_title_en', models.CharField(max_length=250)),
                ('paper_description_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('paper_description_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('paper_description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('paper_date', models.DateField(auto_now_add=True)),
                ('paper_views', models.IntegerField(default=0)),
                ('paper_content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('paper_content_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('paper_content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('paper_tegs', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_journals.journal')),
            ],
            options={
                'verbose_name': 'Papers',
                'verbose_name_plural': 'Papers',
                'db_table': 'papers',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_papers.papers')),
            ],
            options={
                'verbose_name': 'References',
                'verbose_name_plural': 'References',
                'db_table': 'references',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('review_file', models.FileField(blank=True, null=True, upload_to='review_files')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_papers.papers')),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
            },
        ),
    ]
